name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image with Latest Tag
      run: docker build . --file Dockerfile --tag virtualflybrain/jupyterhub:latest

    - name: Tag Docker Image with Main Tag
      run: docker tag virtualflybrain/jupyterhub:latest virtualflybrain/jupyterhub:main

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Latest Tag
      run: docker push virtualflybrain/jupyterhub:latest

    - name: Push Main Tag
      run: docker push virtualflybrain/jupyterhub:main
